// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAugVC7OtiJN2L_oX3G22Tg4SzzfUE4ezw',
    appId: '1:586829157644:web:87594591bbd571fe012529',
    messagingSenderId: '586829157644',
    projectId: 'trendyvibes-6e946',
    authDomain: 'trendyvibes-6e946.firebaseapp.com',
    storageBucket: 'trendyvibes-6e946.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08rXQzr187gwX2A5JXnigI89jTU1EYTE',
    appId: '1:586829157644:android:b075983654b56e96012529',
    messagingSenderId: '586829157644',
    projectId: 'trendyvibes-6e946',
    storageBucket: 'trendyvibes-6e946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByfOD-luvoCf2Dkwyz3vNN0jUZEBqNmCI',
    appId: '1:586829157644:ios:49697a85974d1a90012529',
    messagingSenderId: '586829157644',
    projectId: 'trendyvibes-6e946',
    storageBucket: 'trendyvibes-6e946.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );
}
